#!/applications/R/R-3.5.0/bin/Rscript

# Convert samtools pileup file into a haplotype matrix
# for visualisation of recombination over interval

#sample <- "barcode1_120"
#MAPQ <- 60

args <- commandArgs(trailingOnly = T)
sample <- args[1]
MAPQ <- args[2]

setwd("/home/ajt200/analysis/nanopore/pollen_typing/")
library(dplyr)
library(parallel)
library(doParallel)
registerDoParallel(cores = detectCores())
print("Currently registered parallel backend name, version and cores")
print(getDoParName())
print(getDoParVersion())
print(getDoParWorkers())

# Load reference and alternate alleles
alleles <- read.table("3a_SNPs_in_Col_and_Ws.tsv",
                      header = T)

# Load pileup containing per-alignment genotype information,
# as generated by samtools mpileup
plp <- read.table(paste0("minimap2_TAIR10_",
                         sample,
                         "_sorted_primary_MAPQ", MAPQ, ".plp"),
                  header = F, sep = "\t",
                  quote = "", comment.char = "",
                  stringsAsFactors = F)

# Append the first 3 columns, the alternate allele, and columns
# corresponding to per-alignment file genotype
plp <- data.frame(plp[ ,1:3],
                  alleles[ ,4],
                  plp[ ,seq(from = 5, 
                            to = dim(plp)[2]-1,
                            by = 3)])
colnames(plp) <- c("chr", "pos", "ref", "alt",
                   seq(1:(dim(plp)[2]-4)))
# Replace factors with characters
factorColumns <- sapply(plp, is.factor)
plp[factorColumns] <- lapply(plp[factorColumns], as.character)
plpHap <- plp

# Re-encode haplotypes using genotype naming convention
# to avoid incorrect encoding of adenosine bases
# Col-0 as "AA", Ws-4 as "BB", "*" and all others as "-" 
for(x in 1:(dim(plpHap)[1])) {
  for(y in 5:(dim(plpHap)[2])) {
    if( plpHap[x,y] %in% c(".", ",") ) {
      plpHap[x,y] <- "AA"
    } else if( plpHap[x,y] %in% c(plpHap[x,4],
                                  tolower(plpHap[x,4])) ) {
      plpHap[x,y] <- "BB"
    } else {
      plpHap[x,y] <- "-"
    }
  }
}
# Convert genotype naming convention into
# haplotype naming convention as we cannot derive
# each allele from single-molecule sequencing
plpHap[] <- lapply(plpHap, function(x) as.character(gsub("AA", "A", x)))
plpHap[] <- lapply(plpHap, function(x) as.character(gsub("BB", "B", x)))

# Transpose haplotype matrix for sorting
tplpHap <- data.frame(t(plpHap[,5:dim(plpHap)[2]]))
colnames(tplpHap) <- as.integer(plpHap$pos)

# Add column representing haplotypes as character strings
stringHap <- sapply(1:(dim(tplpHap)[1]), function(x) {
  paste0(as.character(as.matrix(tplpHap[x,])), collapse = "")
})
tplpHap <- data.frame(tplpHap,
                      hap = stringHap)
colnames(tplpHap) <- c(as.integer(plpHap$pos),
                       "hap")
# Replace factors with characters
factorColumns <- sapply(tplpHap, is.factor)
tplpHap[factorColumns] <- lapply(tplpHap[factorColumns], as.character)

# Retain only rows that contain both parental haplotypes
tplpHap <- tplpHap[grepl("A", tplpHap$hap) &
                   grepl("B", tplpHap$hap),]


# Apply a haplotype imputation approach which
# is informed by haplotypes at flanking markers
# and, later, by haplotypes within other alignments

# For imputation of missing haplotypes that are not at
# the ends of an alignment, they must be flanked by
# two of the same parental allele, one on each side
# (e.g., for "AAAA-AAA-AAAAA-BB", only the first and second "-",
#  and not the third "-", would be imputed as "A")
# For Col-0 (A) alleles
while( sum(grepl(pattern = "A(-+)A",
                 x = tplpHap$hap,
                 perl = T)) > 0 ) {
  for(x in 1:length(tplpHap$hap)) {
    if( grepl(pattern = "A(-+)A",
              x = tplpHap$hap[x],
              perl = T) ) {
      tplpHap$hap[x] <- sub(pattern = "A(-+)A",
                            replacement = paste0("A",
                                                 paste0(rep(x = "A",
                                                            times = attr(regexpr(pattern = "A(-+)A",
                                                                                 text = tplpHap$hap[x],
                                                                                 perl = T),
                                                                         'capture.length')[1]),
                                                        collapse = ""),
                                                 "A"),
                            x = tplpHap$hap[x],
                            perl = T)
    }
  }
}
# For Ws-4 (B) alleles
while( sum(grepl(pattern = "B(-+)B",
                 x = tplpHap$hap,
                 perl = T)) > 0 ) {
  for(x in 1:length(tplpHap$hap)) {
    if( grepl(pattern = "B(-+)B",
              x = tplpHap$hap[x],
              perl = T) ) {
      tplpHap$hap[x] <- sub(pattern = "B(-+)B",
                            replacement = paste0("B",
                                                 paste0(rep(x = "B",
                                                            times = attr(regexpr(pattern = "B(-+)B",
                                                                                 text = tplpHap$hap[x],
                                                                                 perl = T),
                                                                         'capture.length')[1]),
                                                        collapse = ""),
                                                 "B"),
                            x = tplpHap$hap[x],
                            perl = T)
    }
  }
}

# Impute missing haplotypes at the ends of an alignment based
# on the haplotype at the nearest marker(s)

# As an allele-specific primer on the left binds only Col-0 (A) alleles,
# impute missing haplotypes at the left-hand side (beginning) of alignments
# that have a Col-0 (A) allele at a marker on their right
# (e.g., for "----ABBBBBBBBBA-", only the left-hand "----" and
#  not the right-hand "-" would be imputed as "A")
# For Col-0 (A) alleles
# left-hand side (beginning) of alignments
while( sum(grepl(pattern = "^(-+)A",
                 x = tplpHap$hap,
                 perl = T)) > 0 ) {
  for(x in 1:length(tplpHap$hap)) {
    if( grepl(pattern = "^(-+)A",
              x = tplpHap$hap[x],
              perl = T) ) {
      tplpHap$hap[x] <- sub(pattern = "^(-+)A",
                            replacement = paste0(paste0(rep(x = "A",
                                                            times = attr(regexpr(pattern = "^(-+)A",
                                                                                 text = tplpHap$hap[x],
                                                                                 perl = T),
                                                                         'capture.length')[1]),
                                                        collapse = ""),
                                                 "A"),
                            x = tplpHap$hap[x],
                            perl = T)
    }
  }
}
## right-hand side (end) of alignments
## (to be used for Col-0 (A) alleles ONLY where a Col-0-specific
##  primer binds the right-hand side of the amplicon)
#while( sum(grepl(pattern = "A(-+)$",
#                 x = tplpHap$hap,
#                 perl = T)) > 0 ) {
#  for(x in 1:length(tplpHap$hap)) {
#    if( grepl(pattern = "A(-+)$",
#              x = tplpHap$hap[x],
#              perl = T) ) {
#      tplpHap$hap[x] <- sub(pattern = "A(-+)$",
#                            replacement = paste0("A",
#                                                 paste0(rep(x = "A",
#                                                            times = attr(regexpr(pattern = "A(-+)$",
#                                                                                 text = tplpHap$hap[x],
#                                                                                 perl = T),
#                                                                         'capture.length')[1]),
#                                                        collapse = "")),
#                            x = tplpHap$hap[x],
#                            perl = T)
#    }
#  }
#}

# As an allele-specific primer on the right binds only Ws-4 (B) alleles,
# impute missing haplotypes at the right-hand side (end) of alignments
# that have a Ws-4 (B) allele at a marker on their left
# (e.g., for "-BAAAAAAAAAB----", only the right-hand "----" and
#  not the left-hand "-" would be imputed as "B")
# For Ws-4 (B) alleles
# right-hand side (end) of alignments
while( sum(grepl(pattern = "B(-+)$",
                 x = tplpHap$hap,
                 perl = T)) > 0 ) {
  for(x in 1:length(tplpHap$hap)) {
    if( grepl(pattern = "B(-+)$",
              x = tplpHap$hap[x],
              perl = T) ) {
      tplpHap$hap[x] <- sub(pattern = "B(-+)$",
                            replacement = paste0("B",
                                                 paste0(rep(x = "B",
                                                            times = attr(regexpr(pattern = "B(-+)$",
                                                                                 text = tplpHap$hap[x],
                                                                                 perl = T),
                                                                         'capture.length')[1]),
                                                        collapse = "")),
                            x = tplpHap$hap[x],
                            perl = T)
    }
  }
}
## (to be used for Ws-4 (B) alleles ONLY where a Ws-4-specific
##  primer binds the left-hand side of the amplicon)
## left-hand side (beginning) of alignments
#while( sum(grepl(pattern = "^(-+)B",
#                 x = tplpHap$hap,
#                 perl = T)) > 0 ) {
#  for(x in 1:length(tplpHap$hap)) {
#    if( grepl(pattern = "^(-+)B",
#              x = tplpHap$hap[x],
#              perl = T) ) {
#      tplpHap$hap[x] <- sub(pattern = "^(-+)B",
#                            replacement = paste0(paste0(rep(x = "B",
#                                                            times = attr(regexpr(pattern = "^(-+)B",
#                                                                                 text = tplpHap$hap[x],
#                                                                                 perl = T),
#                                                                         'capture.length')[1]),
#                                                        collapse = ""),
#                                                 "B"),
#                            x = tplpHap$hap[x],
#                            perl = T)
#    }
#  }
#}

# Order by (imputed) haplotypes
tplpHap_sort <- tplpHap[sort.int(tplpHap$hap,
                                 decreasing = T,
                                 index.return=T)$ix,]
# Group by (imputed) haplotypes
tplpHap_group_n <- tplpHap %>%
  group_by(hap) %>%
  summarize(n())

# Extract the top 1% of haplotypes in terms
# of frequency of occurrence
tplpHap_group_n_quant <- tplpHap_group_n %>%
  filter(`n()` > quantile(`n()`, 0.99))

tplpHap_group_n_v1 <- tplpHap_group_n
tplpHap_group_n_quant_v1 <- tplpHap_group_n_quant

# For those haplotypes in the top 1% which contain "-",
# impute "-" as "A" or "B" proportional to the observed
# frequency of occurrence of the two otherwise matching
# haplotypes
# (e.g., "A-BBBBBBBBBBBBBB" occurs 130 times,
#        "AABBBBBBBBBBBBBB" occurs 550 times,   
#        "ABBBBBBBBBBBBBBB" occurs 2332 times;
#  550 + round( 130 * ( 550 / (550+2332) ) ) = 575 "AABBBBBBBBBBBBBB" occurrences after imputation
#  2332 + round( 130 * ( 2332 / (550+2332) ) ) = 2437 "ABBBBBBBBBBBBBBB" occurrences after imputation
while( sum(grepl(pattern = "-",
                 x = tplpHap_group_n_quant$hap,
                 perl = T)) > 0 ) {
  for(x in 1:length(tplpHap_group_n_quant$hap)) {
    if( grepl(pattern = "-",
              x = tplpHap_group_n_quant$hap[x],
              perl = T) ) {
      impA <- sub(pattern = "-",
                  replacement = "A",
                  x = tplpHap_group_n_quant$hap[x],
                  perl = T)
      impB <- sub(pattern = "-",
                  replacement = "B",
                  x = tplpHap_group_n_quant$hap[x],
                  perl = T)
      hapNfreq <- tplpHap_group_n_quant$`n()`[x]
      hapAfreq <- tplpHap_group_n$`n()`[tplpHap_group_n$hap %in% impA]
      hapBfreq <- tplpHap_group_n$`n()`[tplpHap_group_n$hap %in% impB]
      # If impA or impB are not present in tplpHap_group_n$hap (unlikely),
      # redefine zero-length integer vector ( integer(0) ) with 0
      if( !length(hapAfreq) ) { hapAfreq <- 0 }
      if( !length(hapBfreq) ) { hapBfreq <- 0 }
      if( hapAfreq + hapBfreq >= 1 ) {
        hapNfreqA <- round( hapNfreq * ( hapAfreq / ( hapAfreq + hapBfreq ) ) )
        hapNfreqB <- round( hapNfreq * ( hapBfreq / ( hapAfreq + hapBfreq ) ) )
        imphapAfreq <- hapAfreq + hapNfreqA
        print(paste0("Augmented haplotype frequency for ",
                     impA, " = ", imphapAfreq))
        imphapBfreq <- hapBfreq + hapNfreqB
        print(paste0("Augmented haplotype frequency for ",
                     impB, " = ", imphapBfreq))
        # Sanity check
        if( ( imphapAfreq + imphapBfreq ) != ( hapNfreq + hapAfreq + hapBfreq ) ) {
          stop(paste0("Augmented haplotype frequencies for ",
                      tplpHap_group_n_quant$hap[x],
                      " do not add up to summed frequencies for ",
                      tplpHap_group_n_quant$hap[x], " , ",
                      impA, " , and ",
                      impB, " !"))
        }
      } else {
      stop(paste0("Complete versions of haplotype ",
                  tplpHap_group_n_quant$hap[x],
                  " are not present in the alignment dataset!"))
      }
      # Replace haplotypes in tplpHap$hap matching tplpHap_group_n_quant$hap[x]
      # with imputed haplotypes proportional to the observed
      # frequency of occurrence of the two otherwise matching haplotypes
      # which have "A" or "B" at the marker with "-" in tplpHap_group_n_quant$hap[x]
      tplpHap[tplpHap$hap == tplpHap_group_n_quant$hap[x],]$hap <- c(rep(x = impA,
                                                                         times = hapNfreqA),
                                                                     rep(x = impB,
                                                                         times = hapNfreqB))
    }
  }
  # Group by (imputed) haplotypes
  tplpHap_group_n <- tplpHap %>%
    group_by(hap) %>%
    summarize(n())
  
  # Extract the top 1% of haplotypes in terms
  # of frequency of occurrence
  tplpHap_group_n_quant <- tplpHap_group_n %>%
    filter(`n()` > quantile(`n()`, 0.99))
}

# Convert haplotype frequencies into proportions
tplpHap_group_n_quant$`n()` / (sum(tplpHap_group_n_quant$`n()`))

tmp <- arrange(tplpHap,
               desc(tplpHap[,1]),
	       desc(tplpHap[,2]),
               desc(tplpHap[,3]),
               desc(tplpHap[,4]),
               desc(tplpHap[,5]),
               desc(tplpHap[,6]),
               desc(tplpHap[,7]),
               desc(tplpHap[,8]),
               desc(tplpHap[,9]),
               desc(tplpHap[,10]),
               desc(tplpHap[,11]),
               desc(tplpHap[,12]),
               desc(tplpHap[,13]),
               desc(tplpHap[,14]),
               desc(tplpHap[,15]),
               desc(tplpHap[,16]))

tmp2 <- arrange(tbl_df(tplpHap),
               desc(tplpHap[,1:16]))
	       desc(tplpHap[,2]),
               desc(tplpHap[,3]),
               desc(tplpHap[,4]),
               desc(tplpHap[,6]),
               desc(tplpHap[,6]),
               desc(tplpHap[,7]),
               desc(tplpHap[,8]),
               desc(tplpHap[,9]),
               desc(tplpHap[,10]),
               desc(tplpHap[,11]),
               desc(tplpHap[,12]),
               desc(tplpHap[,13]),
               desc(tplpHap[,14]),
               desc(tplpHap[,15]),
               desc(tplpHap[,16]))

tmp <- tplpHap[order(
                     tplpHap[,1],
		     tplpHap[,2],
                     tplpHap[,3],
                     tplpHap[,4],
                     tplpHap[,6],
                     tplpHap[,6],
                     tplpHap[,7],
                     tplpHap[,8],
                     tplpHap[,9],
                     tplpHap[,10],
                     tplpHap[,11],
                     tplpHap[,12],
                     tplpHap[,13],
                     tplpHap[,14],
                     tplpHap[,15],
                     tplpHap[,16]
                    ),]
