#!bin/bash

# Natasha Yelina PCR-amplified the crossover hotspot 3a
# using pooled DNA extracted from pollen of 5 different sample types,
# each derived from a Col-0 x Ws-4 cross, and some with MTOPVIB guided to 3a.
# Matt Naish Nanopore-sequenced these amplicons

# This is Matt Naish's script for aligning resultant adapter-trimmed
# FASTQ files (with improved base calling) to TAIR10 using
# Minimap2 v2.17-r941

# The output BAM files generated by this script will be used for
# detection of potential recombination breakpoints with downstream analyses

# Usage on node7:
# /scripts/csmit -m 100G -c 32 "bash ./minimap2.sh 32 4"

threads=$1
memory=$2

#Activate pomoxis envir
source activate pomoxis

[[ -d bam/ ]] || mkdir bam/

# Loop through barcodes 1 to 5
for i in {1..5}
do
  minimap2 -a -x map-ont -r 10000 -t ${threads} TAIR10_chr_all.fa fastq/Pollentyping_barcode_${i}_porechopped.fq > minimap2_TAIR10_Pollentyping_barcode_${i}.sam

  # Convert to .bam and create index file for visualisation
  samtools view -S -b minimap2_TAIR10_Pollentyping_barcode_${i}.sam | samtools sort -@ ${threads} -m ${memory}G -o minimap2_TAIR10_Pollentyping_barcode_${i}_sorted.bam

  samtools index minimap2_TAIR10_Pollentyping_barcode_${i}_sorted.bam

  #samtools view -S -b   ngmlr_filtered_trimmed.sam >  ngmlr_filtered_trimmed.bam

  # Delete .sam file generated
  rm minimap2_TAIR10_Pollentyping_barcode_${i}.sam

  # Move .bam file
  mv minimap2_TAIR10_Pollentyping_barcode_${i}_sorted.bam bam/
done

source deactivate
